version: '3.9'
networks:
  kent_network:
    name: kent_network
services:
  tools:
    build:
      context: .
    expose:
      - 8087
    environment:
      - APP_PORT=8087
    volumes:
      - ./data:/app/data
    profiles:
      - tools
    networks:
      - kent_network